# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-24 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitHubRelationship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborate_duckduckgo_zeroclickinfo_goodies_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_duckduckgo_zeroclickinfo_goodies_nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_jquery_jquery_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_jquery_jquery_nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_puppetlabs_puppetdb_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_puppetlabs_puppetdb_nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_rails_rails_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_rails_rails_nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_saltstack_salt_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_saltstack_salt_nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_duckduckgo_zeroclickinfo_goodies_nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_duckduckgo_zeroclickinfo_goodiesy_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_jquery_jquery_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_jquery_jquery_nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_puppetlabs_puppetdb_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_puppetlabs_puppetdb_nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_rails_rails_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_rails_rails_nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_saltstack_salt_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_saltstack_salt_nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.TextField(max_length=256)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='commit_saltstack_salt_edges',
            unique_together=set([('target', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='commit_rails_rails_edges',
            unique_together=set([('target', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='commit_puppetlabs_puppetdb_edges',
            unique_together=set([('target', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='commit_jquery_jquery_edges',
            unique_together=set([('target', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='commit_duckduckgo_zeroclickinfo_goodiesy_edges',
            unique_together=set([('target', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='collaborate_saltstack_salt_edges',
            unique_together=set([('target', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='collaborate_rails_rails_edges',
            unique_together=set([('target', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='collaborate_puppetlabs_puppetdb_edges',
            unique_together=set([('target', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='collaborate_jquery_jquery_edges',
            unique_together=set([('target', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='collaborate_duckduckgo_zeroclickinfo_goodies_edges',
            unique_together=set([('target', 'source')]),
        ),
    ]
