# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-31 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitHubRelationship', '0004_auto_20170601_0151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commit_duckduckgo_zeroclickinfo_goodiesy_edges',
            new_name='Commit_duckduckgo_zeroclickinfo_goodies_edges',
        ),
    ]
