# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GitHubRelationship', '0005_auto_20170601_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborate_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField(max_length=256, verbose_name='project')),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborate_nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField(max_length=256, verbose_name='project')),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField(max_length=256, verbose_name='project')),
                ('target', models.IntegerField(verbose_name='target')),
                ('source', models.IntegerField(verbose_name='source')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commit_nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField(max_length=256, verbose_name='project')),
                ('uid', models.IntegerField(verbose_name='uid')),
                ('label', models.TextField(max_length=256)),
                ('modularity', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('inDegree', models.IntegerField(default=0)),
                ('outDegree', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='commit_nodes',
            unique_together=set([('project', 'uid')]),
        ),
        migrations.AlterUniqueTogether(
            name='commit_edges',
            unique_together=set([('project', 'target', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='collaborate_nodes',
            unique_together=set([('project', 'uid')]),
        ),
        migrations.AlterUniqueTogether(
            name='collaborate_edges',
            unique_together=set([('project', 'target', 'source')]),
        ),
    ]
