# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-11 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitHubRelationship', '0006_auto_20170612_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collaborate_duckduckgo_zeroclickinfo_goodies_edges',
        ),
        migrations.DeleteModel(
            name='Collaborate_duckduckgo_zeroclickinfo_goodies_nodes',
        ),
        migrations.DeleteModel(
            name='Collaborate_jquery_jquery_edges',
        ),
        migrations.DeleteModel(
            name='Collaborate_jquery_jquery_nodes',
        ),
        migrations.DeleteModel(
            name='Collaborate_netty_netty_edges',
        ),
        migrations.DeleteModel(
            name='Collaborate_netty_netty_nodes',
        ),
        migrations.DeleteModel(
            name='Collaborate_puppetlabs_puppetdb_edges',
        ),
        migrations.DeleteModel(
            name='Collaborate_puppetlabs_puppetdb_nodes',
        ),
        migrations.DeleteModel(
            name='Collaborate_rails_rails_edges',
        ),
        migrations.DeleteModel(
            name='Collaborate_rails_rails_nodes',
        ),
        migrations.DeleteModel(
            name='Collaborate_saltstack_salt_edges',
        ),
        migrations.DeleteModel(
            name='Collaborate_saltstack_salt_nodes',
        ),
        migrations.DeleteModel(
            name='Commit_duckduckgo_zeroclickinfo_goodies_edges',
        ),
        migrations.DeleteModel(
            name='Commit_duckduckgo_zeroclickinfo_goodies_nodes',
        ),
        migrations.DeleteModel(
            name='Commit_jquery_jquery_edges',
        ),
        migrations.DeleteModel(
            name='Commit_jquery_jquery_nodes',
        ),
        migrations.DeleteModel(
            name='Commit_netty_netty_edges',
        ),
        migrations.DeleteModel(
            name='Commit_netty_netty_nodes',
        ),
        migrations.DeleteModel(
            name='Commit_puppetlabs_puppetdb_edges',
        ),
        migrations.DeleteModel(
            name='Commit_puppetlabs_puppetdb_nodes',
        ),
        migrations.DeleteModel(
            name='Commit_rails_rails_edges',
        ),
        migrations.DeleteModel(
            name='Commit_rails_rails_nodes',
        ),
        migrations.DeleteModel(
            name='Commit_saltstack_salt_edges',
        ),
        migrations.DeleteModel(
            name='Commit_saltstack_salt_nodes',
        ),
    ]
